<?xml version='1.0' standalone='yes' ?>
<LVData xmlns="http://www.ni.com/LVData">
<Version>18.0</Version>
<Cluster>
<Name></Name>
<NumElts>2</NumElts>
<Array>
<Name>Actions</Name>
<Dimsize>6</Dimsize>
<Cluster>
<Name>Action</Name>
<NumElts>7</NumElts>
<Boolean>
<Name>Toggle</Name>
<Val>1</Val>
</Boolean>
<Boolean>
<Name>Open parameter editor</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Open MacroEditor</Name>
<Val>0</Val>
</Boolean>
<Path>
<Name>Macro path</Name>
<Val></Val>
</Path>
<DBL>
<Name>&lt;-- Duration (s)</Name>
<Val>0.10000000000000</Val>
</DBL>
<Array>
<Name>Parameters</Name>
<Dimsize>10</Dimsize>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Source Coils enable (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>1.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>1</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Moderator Bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>88.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>1</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>g1 bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>g2 bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>g3 bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Higaki B charge (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Transfer Line enable (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Only Extr. Coil enable -&gt; on MCP (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Pulser voltage (divided by 160)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>0</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val></Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
</Array>
<String>
<Name>Comment</Name>
<Val>RGS bias on</Val>
</String>
</Cluster>
<Cluster>
<Name>Action</Name>
<NumElts>7</NumElts>
<Boolean>
<Name>Toggle</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Open parameter editor</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Open MacroEditor</Name>
<Val>0</Val>
</Boolean>
<Path>
<Name>Macro path</Name>
<Val>C:\CuspControl\Positron\1_Macros\Util\Beamblock-trapelectrodes-part1.mac</Val>
</Path>
<DBL>
<Name>&lt;-- Duration (s)</Name>
<Val>10.00100000000000</Val>
</DBL>
<Array>
<Name>Parameters</Name>
<Dimsize>10</Dimsize>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Source Coils enable (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>1.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Moderator Bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>88.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>g1 bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>g2 bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>g3 bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Higaki B charge (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Transfer Line enable (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Only Extr. Coil enable -&gt; on MCP (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Pulser voltage (divided by 160)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>0</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val></Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
</Array>
<String>
<Name>Comment</Name>
<Val>wait 10s</Val>
</String>
</Cluster>
<Cluster>
<Name>Action</Name>
<NumElts>7</NumElts>
<Boolean>
<Name>Toggle</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Open parameter editor</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Open MacroEditor</Name>
<Val>0</Val>
</Boolean>
<Path>
<Name>Macro path</Name>
<Val>C:\CuspControl\Positron\1_Macros\Util\G4test.mac</Val>
</Path>
<DBL>
<Name>&lt;-- Duration (s)</Name>
<Val>10.00100000000000</Val>
</DBL>
<Array>
<Name>Parameters</Name>
<Dimsize>10</Dimsize>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Source Coils enable (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>1.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Moderator Bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>88.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>g1 bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>g2 bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>g3 bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Higaki B charge (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Transfer Line enable (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Only Extr. Coil enable -&gt; on MCP (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Pulser voltage (divided by 160)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>0</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val></Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
</Array>
<String>
<Name>Comment</Name>
<Val></Val>
</String>
</Cluster>
<Cluster>
<Name>Action</Name>
<NumElts>7</NumElts>
<Boolean>
<Name>Toggle</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Open parameter editor</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Open MacroEditor</Name>
<Val>0</Val>
</Boolean>
<Path>
<Name>Macro path</Name>
<Val>C:\CuspControl\Positron\1_Macros\Util\Beamblock-trapelectrodes-part3.mac</Val>
</Path>
<DBL>
<Name>&lt;-- Duration (s)</Name>
<Val>10.01100000000000</Val>
</DBL>
<Array>
<Name>Parameters</Name>
<Dimsize>10</Dimsize>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Source Coils enable (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>1.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Moderator Bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>88.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>g1 bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>g2 bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>g3 bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Higaki B charge (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Transfer Line enable (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Only Extr. Coil enable -&gt; on MCP (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Pulser voltage (divided by 160)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>0</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val></Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
</Array>
<String>
<Name>Comment</Name>
<Val>ramp down electrodes, wait 10s</Val>
</String>
</Cluster>
<Cluster>
<Name>Action</Name>
<NumElts>7</NumElts>
<Boolean>
<Name>Toggle</Name>
<Val>1</Val>
</Boolean>
<Boolean>
<Name>Open parameter editor</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Open MacroEditor</Name>
<Val>0</Val>
</Boolean>
<Path>
<Name>Macro path</Name>
<Val></Val>
</Path>
<DBL>
<Name>&lt;-- Duration (s)</Name>
<Val>1.00000000000000</Val>
</DBL>
<Array>
<Name>Parameters</Name>
<Dimsize>10</Dimsize>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Source Coils enable (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>1</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Moderator Bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>1</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>g1 bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>g2 bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>g3 bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Higaki B charge (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Transfer Line enable (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Only Extr. Coil enable -&gt; on MCP (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Pulser voltage (divided by 160)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>0</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val></Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
</Array>
<String>
<Name>Comment</Name>
<Val>turn off moderator bias and source coils</Val>
</String>
</Cluster>
<Cluster>
<Name>Action</Name>
<NumElts>7</NumElts>
<Boolean>
<Name>Toggle</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Open parameter editor</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Open MacroEditor</Name>
<Val>0</Val>
</Boolean>
<Path>
<Name>Macro path</Name>
<Val>C:\CuspControl\Positron\1_Macros\Util\ZeroAll.mac</Val>
</Path>
<DBL>
<Name>&lt;-- Duration (s)</Name>
<Val>2.00000000000000E-3</Val>
</DBL>
<Array>
<Name>Parameters</Name>
<Dimsize>10</Dimsize>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Source Coils enable (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Moderator Bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>g1 bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>g2 bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>g3 bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Higaki B charge (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Transfer Line enable (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Only Extr. Coil enable -&gt; on MCP (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Pulser voltage (divided by 160)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>0</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val></Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
</Array>
<String>
<Name>Comment</Name>
<Val></Val>
</String>
</Cluster>
</Array>
<Cluster>
<Name>output cluster</Name>
<NumElts>2</NumElts>
<DBL>
<Name>Total
Time (s)</Name>
<Val>31.11499999999999</Val>
</DBL>
<String>
<Name>Cue Description</Name>
<Val>Turn on RGS bias (10 V) and Source coils, open trap entrance GV</Val>
</String>
</Cluster>
</Cluster>
</LVData>