<?xml version='1.0' standalone='yes' ?>
<LVData xmlns="http://www.ni.com/LVData">
<Version>18.0.1</Version>
<Cluster>
<Name></Name>
<NumElts>2</NumElts>
<Array>
<Name>Actions</Name>
<Dimsize>1</Dimsize>
<Cluster>
<Name>Action</Name>
<NumElts>8</NumElts>
<Boolean>
<Name>Toggle</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Open parameter editor</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Open MacroEditor</Name>
<Val>0</Val>
</Boolean>
<Path>
<Name>Macro path</Name>
<Val>C:\CuspControl\Positron\1_Macros\Test\timing1.mac</Val>
</Path>
<DBL>
<Name>Duration (s)</Name>
<Val>0.33000000000000</Val>
</DBL>
<Array>
<Name>Parameters</Name>
<Dimsize>9</Dimsize>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>0</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>e- block bias (V) [-9 V]</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>e- filament bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>0</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>e- current (A) [0.3 A limit]</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>e- ramp time (s)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>e- source ON (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>0</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val></Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>0</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>e+ accumulation time (s)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>0</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>e+ escape energy (eV)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>0</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val></Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
</Array>
<String>
<Name>Comment</Name>
<Val>timing test</Val>
</String>
<I32>
<Name>Reps</Name>
<Val>1</Val>
</I32>
</Cluster>
</Array>
<Cluster>
<Name>output cluster</Name>
<NumElts>2</NumElts>
<DBL>
<Name>Total
Time (s)</Name>
<Val>0.33000000000000</Val>
</DBL>
<String>
<Name>Cue Description</Name>
<Val>one macro</Val>
</String>
</Cluster>
</Cluster>
</LVData>