<?xml version='1.0' standalone='yes' ?>
<LVData xmlns="http://www.ni.com/LVData">
<Version>18.0.1</Version>
<Cluster>
<Name></Name>
<NumElts>2</NumElts>
<Array>
<Name>Actions</Name>
<Dimsize>3</Dimsize>
<Cluster>
<Name>Action</Name>
<NumElts>8</NumElts>
<Boolean>
<Name>Toggle</Name>
<Val>1</Val>
</Boolean>
<Boolean>
<Name>Open parameter editor</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Open MacroEditor</Name>
<Val>0</Val>
</Boolean>
<Path>
<Name>Macro path</Name>
<Val></Val>
</Path>
<DBL>
<Name>Duration (s)</Name>
<Val>1.00000000000000E-3</Val>
</DBL>
<Array>
<Name>Parameters</Name>
<Dimsize>20</Dimsize>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>ADC</Val>
</String>
<String>
<Name>Name</Name>
<Val>state (0,1,2)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>Camera</Val>
</String>
<String>
<Name>Name</Name>
<Val>state (0,1)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>1.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>1</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>Slave</Val>
</String>
<String>
<Name>Name</Name>
<Val>state (0,1)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>Wait</Val>
</String>
<String>
<Name>Name</Name>
<Val>inbit (0...7)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>e-</Val>
</String>
<String>
<Name>Name</Name>
<Val>enable (0,1)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>e-</Val>
</String>
<String>
<Name>Name</Name>
<Val>burn time (s)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>e-</Val>
</String>
<String>
<Name>Name</Name>
<Val>filament (A)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>RW</Val>
</String>
<String>
<Name>Name</Name>
<Val>enable (0,1)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>RW</Val>
</String>
<String>
<Name>Name</Name>
<Val>frequency (Hz)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>RW</Val>
</String>
<String>
<Name>Name</Name>
<Val>amplitude (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>RW</Val>
</String>
<String>
<Name>Name</Name>
<Val>phase dif (deg)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>HVpulse</Val>
</String>
<String>
<Name>Name</Name>
<Val>enable (0,1)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>HVpulse</Val>
</String>
<String>
<Name>Name</Name>
<Val>amplitude (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>HVpulse</Val>
</String>
<String>
<Name>Name</Name>
<Val>polarity (0=n)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>HVptime</Val>
</String>
<String>
<Name>Name</Name>
<Val>delay (s)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>HVptime</Val>
</String>
<String>
<Name>Name</Name>
<Val>width (s)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>Gcoil</Val>
</String>
<String>
<Name>Name</Name>
<Val>current (A)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>MCP</Val>
</String>
<String>
<Name>Name</Name>
<Val>front bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>MCP</Val>
</String>
<String>
<Name>Name</Name>
<Val>back bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>MCP</Val>
</String>
<String>
<Name>Name</Name>
<Val>phos bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
</Array>
<String>
<Name>Comment</Name>
<Val></Val>
</String>
<I32>
<Name>Reps</Name>
<Val>1</Val>
</I32>
</Cluster>
<Cluster>
<Name>Action</Name>
<NumElts>8</NumElts>
<Boolean>
<Name>Toggle</Name>
<Val>1</Val>
</Boolean>
<Boolean>
<Name>Open parameter editor</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Open MacroEditor</Name>
<Val>0</Val>
</Boolean>
<Path>
<Name>Macro path</Name>
<Val></Val>
</Path>
<DBL>
<Name>Duration (s)</Name>
<Val>1.10000000000000E-2</Val>
</DBL>
<Array>
<Name>Parameters</Name>
<Dimsize>20</Dimsize>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>ADC</Val>
</String>
<String>
<Name>Name</Name>
<Val>state (0,1,2)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>Camera</Val>
</String>
<String>
<Name>Name</Name>
<Val>state (0,1)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>1.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>Slave</Val>
</String>
<String>
<Name>Name</Name>
<Val>state (0,1)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>Wait</Val>
</String>
<String>
<Name>Name</Name>
<Val>inbit (0...7)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>e-</Val>
</String>
<String>
<Name>Name</Name>
<Val>enable (0,1)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>e-</Val>
</String>
<String>
<Name>Name</Name>
<Val>burn time (s)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>e-</Val>
</String>
<String>
<Name>Name</Name>
<Val>filament (A)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>RW</Val>
</String>
<String>
<Name>Name</Name>
<Val>enable (0,1)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>RW</Val>
</String>
<String>
<Name>Name</Name>
<Val>frequency (Hz)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>RW</Val>
</String>
<String>
<Name>Name</Name>
<Val>amplitude (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>RW</Val>
</String>
<String>
<Name>Name</Name>
<Val>phase dif (deg)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>1.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>1</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>HVpulse</Val>
</String>
<String>
<Name>Name</Name>
<Val>enable (0,1)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>HVpulse</Val>
</String>
<String>
<Name>Name</Name>
<Val>amplitude (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>HVpulse</Val>
</String>
<String>
<Name>Name</Name>
<Val>polarity (0=n)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>HVptime</Val>
</String>
<String>
<Name>Name</Name>
<Val>delay (s)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>HVptime</Val>
</String>
<String>
<Name>Name</Name>
<Val>width (s)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>Gcoil</Val>
</String>
<String>
<Name>Name</Name>
<Val>current (A)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>MCP</Val>
</String>
<String>
<Name>Name</Name>
<Val>front bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>MCP</Val>
</String>
<String>
<Name>Name</Name>
<Val>back bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>MCP</Val>
</String>
<String>
<Name>Name</Name>
<Val>phos bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
</Array>
<String>
<Name>Comment</Name>
<Val></Val>
</String>
<I32>
<Name>Reps</Name>
<Val>1</Val>
</I32>
</Cluster>
<Cluster>
<Name>Action</Name>
<NumElts>8</NumElts>
<Boolean>
<Name>Toggle</Name>
<Val>1</Val>
</Boolean>
<Boolean>
<Name>Open parameter editor</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Open MacroEditor</Name>
<Val>0</Val>
</Boolean>
<Path>
<Name>Macro path</Name>
<Val></Val>
</Path>
<DBL>
<Name>Duration (s)</Name>
<Val>1.10000000000000E-2</Val>
</DBL>
<Array>
<Name>Parameters</Name>
<Dimsize>20</Dimsize>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>ADC</Val>
</String>
<String>
<Name>Name</Name>
<Val>state (0,1,2)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>Camera</Val>
</String>
<String>
<Name>Name</Name>
<Val>state (0,1)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>1</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>Slave</Val>
</String>
<String>
<Name>Name</Name>
<Val>state (0,1)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>Wait</Val>
</String>
<String>
<Name>Name</Name>
<Val>inbit (0...7)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>e-</Val>
</String>
<String>
<Name>Name</Name>
<Val>enable (0,1)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>1.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>1</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>e-</Val>
</String>
<String>
<Name>Name</Name>
<Val>burn time (s)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>30.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>1</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>e-</Val>
</String>
<String>
<Name>Name</Name>
<Val>filament (A)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.30000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>1</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>RW</Val>
</String>
<String>
<Name>Name</Name>
<Val>enable (0,1)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>RW</Val>
</String>
<String>
<Name>Name</Name>
<Val>frequency (Hz)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>RW</Val>
</String>
<String>
<Name>Name</Name>
<Val>amplitude (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>5.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>1</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>RW</Val>
</String>
<String>
<Name>Name</Name>
<Val>phase dif (deg)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>2.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>1</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>HVpulse</Val>
</String>
<String>
<Name>Name</Name>
<Val>enable (0,1)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>HVpulse</Val>
</String>
<String>
<Name>Name</Name>
<Val>amplitude (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>HVpulse</Val>
</String>
<String>
<Name>Name</Name>
<Val>polarity (0=n)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>5.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>1</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>HVptime</Val>
</String>
<String>
<Name>Name</Name>
<Val>delay (s)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>HVptime</Val>
</String>
<String>
<Name>Name</Name>
<Val>width (s)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>Gcoil</Val>
</String>
<String>
<Name>Name</Name>
<Val>current (A)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>3.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>1</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>MCP</Val>
</String>
<String>
<Name>Name</Name>
<Val>front bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>MCP</Val>
</String>
<String>
<Name>Name</Name>
<Val>back bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<String>
<Name>Status</Name>
<Val>MCP</Val>
</String>
<String>
<Name>Name</Name>
<Val>phos bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
</Array>
<String>
<Name>Comment</Name>
<Val></Val>
</String>
<I32>
<Name>Reps</Name>
<Val>1</Val>
</I32>
</Cluster>
</Array>
<Cluster>
<Name>output cluster</Name>
<NumElts>2</NumElts>
<DBL>
<Name>Total
Time (s)</Name>
<Val>0.62300000000000</Val>
</DBL>
<String>
<Name>Cue Description</Name>
<Val>parameter changes</Val>
</String>
</Cluster>
</Cluster>
</LVData>