<?xml version='1.0' standalone='yes' ?>
<LVData xmlns="http://www.ni.com/LVData">
<Version>18.0</Version>
<Cluster>
<Name>MacroSaveCluster</Name>
<NumElts>5</NumElts>
<Array>
<Name>Instructions</Name>
<Dimsize>3</Dimsize>
<Cluster>
<Name>Instruction</Name>
<NumElts>9</NumElts>
<DBL>
<Name>Duration</Name>
<Val>1.00000000000000E-3</Val>
</DBL>
<String>
<Name>Comment</Name>
<Val>init</Val>
</String>
<Array>
<Name>Input Bits</Name>
<Dimsize>16</Dimsize>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
</Array>
<I32>
<Name>Steps</Name>
<Val>1</Val>
</I32>
<Boolean>
<Name>Edit Potential</Name>
<Val>0</Val>
</Boolean>
<Array>
<Name>Output Bits</Name>
<Dimsize>38</Dimsize>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
</Array>
<Path>
<Name>Macro Path</Name>
<Val></Val>
</Path>
<Array>
<Name>Potentials</Name>
<Dimsize>18</Dimsize>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
</Array>
<Boolean>
<Name>Ramp/Point</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Instruction</Name>
<NumElts>9</NumElts>
<DBL>
<Name>Duration</Name>
<Val>0.30000000000000</Val>
</DBL>
<String>
<Name>Comment</Name>
<Val>Raise potentials</Val>
</String>
<Array>
<Name>Input Bits</Name>
<Dimsize>16</Dimsize>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
</Array>
<I32>
<Name>Steps</Name>
<Val>3000</Val>
</I32>
<Boolean>
<Name>Edit Potential</Name>
<Val>0</Val>
</Boolean>
<Array>
<Name>Output Bits</Name>
<Dimsize>38</Dimsize>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
</Array>
<Path>
<Name>Macro Path</Name>
<Val></Val>
</Path>
<Array>
<Name>Potentials</Name>
<Dimsize>18</Dimsize>
<DBL>
<Name></Name>
<Val>115.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>115.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>80.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>57.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>57.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>63.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>66.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>69.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>70.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>70.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>70.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>70.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>70.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>70.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>71.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>74.50000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>78.50000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>82.00000000000003</Val>
</DBL>
</Array>
<Boolean>
<Name>Ramp/Point</Name>
<Val>1</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Instruction</Name>
<NumElts>9</NumElts>
<DBL>
<Name>Duration</Name>
<Val>5.00000000000000E-2</Val>
</DBL>
<String>
<Name>Comment</Name>
<Val>Final state</Val>
</String>
<Array>
<Name>Input Bits</Name>
<Dimsize>16</Dimsize>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
</Array>
<I32>
<Name>Steps</Name>
<Val>1</Val>
</I32>
<Boolean>
<Name>Edit Potential</Name>
<Val>0</Val>
</Boolean>
<Array>
<Name>Output Bits</Name>
<Dimsize>38</Dimsize>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
</Array>
<Path>
<Name>Macro Path</Name>
<Val></Val>
</Path>
<Array>
<Name>Potentials</Name>
<Dimsize>18</Dimsize>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
</Array>
<Boolean>
<Name>Ramp/Point</Name>
<Val>0</Val>
</Boolean>
</Cluster>
</Array>
<Array>
<Name>Changes</Name>
<Dimsize>3</Dimsize>
<Dimsize>3</Dimsize>
<Boolean>
<Name></Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name></Name>
<Val>1</Val>
</Boolean>
<Boolean>
<Name></Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name></Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name></Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name></Name>
<Val>1</Val>
</Boolean>
<Boolean>
<Name></Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name></Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name></Name>
<Val>0</Val>
</Boolean>
</Array>
<String>
<Name>Macro Description</Name>
<Val>Prepare Potential for Extraction
x = do nothing (skip)</Val>
</String>
<DBL>
<Name>Total Time (s)</Name>
<Val>0.35100000000000</Val>
</DBL>
<DBL>
<Name>Samples per sec</Name>
<Val>10000.00000000000000</Val>
</DBL>
</Cluster>
</LVData>