<?xml version='1.0' standalone='yes' ?>
<LVData xmlns="http://www.ni.com/LVData">
<Version>18.0</Version>
<Cluster>
<Name></Name>
<NumElts>2</NumElts>
<Array>
<Name>Actions</Name>
<Dimsize>1</Dimsize>
<Cluster>
<Name>Action</Name>
<NumElts>7</NumElts>
<Boolean>
<Name>Toggle</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Open parameter editor</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Open MacroEditor</Name>
<Val>0</Val>
</Boolean>
<Path>
<Name>Macro path</Name>
<Val>C:\CuspControl\Positron\1_Macros\Test\2021-08-04\20V_m2.mac</Val>
</Path>
<DBL>
<Name>&lt;-- Duration (s)</Name>
<Val>2.00000000000000E-3</Val>
</DBL>
<Array>
<Name>Parameters</Name>
<Dimsize>11</Dimsize>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Source Coils enable (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Moderator Bias (V)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Higaki B charge (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Transfer Line enable (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Only Extr. Coil enable -&gt; on MCP (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>0</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val></Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>p-source trans coils enable (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>0</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val></Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>0</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val></Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>RGS Coils enable (1 or 0)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Status_Name_Value</Name>
<NumElts>4</NumElts>
<Boolean>
<Name>Status</Name>
<Val>1</Val>
</Boolean>
<String>
<Name>Name</Name>
<Val>Pulser voltage (divided by 160)</Val>
</String>
<DBL>
<Name>Value</Name>
<Val>0.00000000000000</Val>
</DBL>
<Boolean>
<Name>Changed</Name>
<Val>0</Val>
</Boolean>
</Cluster>
</Array>
<String>
<Name>Comment</Name>
<Val></Val>
</String>
</Cluster>
</Array>
<Cluster>
<Name>output cluster</Name>
<NumElts>2</NumElts>
<DBL>
<Name>Total
Time (s)</Name>
<Val>2.00000000000000E-3</Val>
</DBL>
<String>
<Name>Cue Description</Name>
<Val></Val>
</String>
</Cluster>
</Cluster>
</LVData>