<?xml version='1.0' standalone='yes' ?>
<LVData xmlns="http://www.ni.com/LVData">
<Version>18.0</Version>
<Cluster>
<Name>MacroSaveCluster</Name>
<NumElts>5</NumElts>
<Array>
<Name>Instructions</Name>
<Dimsize>2</Dimsize>
<Cluster>
<Name>Instruction</Name>
<NumElts>9</NumElts>
<DBL>
<Name>Duration</Name>
<Val>1.00000000000000E-3</Val>
</DBL>
<String>
<Name>Comment</Name>
<Val>initial state</Val>
</String>
<Array>
<Name>Input Bits</Name>
<Dimsize>16</Dimsize>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
</Array>
<I32>
<Name>Steps</Name>
<Val>1</Val>
</I32>
<Boolean>
<Name>Edit Potential</Name>
<Val>0</Val>
</Boolean>
<Array>
<Name>Output Bits</Name>
<Dimsize>38</Dimsize>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
</Array>
<Path>
<Name>Macro Path</Name>
<Val></Val>
</Path>
<Array>
<Name>Potentials</Name>
<Dimsize>18</Dimsize>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
</Array>
<Boolean>
<Name>Ramp/Point</Name>
<Val>0</Val>
</Boolean>
</Cluster>
<Cluster>
<Name>Instruction</Name>
<NumElts>9</NumElts>
<DBL>
<Name>Duration</Name>
<Val>1.00000000000000E-3</Val>
</DBL>
<String>
<Name>Comment</Name>
<Val>20 V on m3</Val>
</String>
<Array>
<Name>Input Bits</Name>
<Dimsize>16</Dimsize>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Input Bit</Name>
<Val>0</Val>
</Boolean>
</Array>
<I32>
<Name>Steps</Name>
<Val>1</Val>
</I32>
<Boolean>
<Name>Edit Potential</Name>
<Val>0</Val>
</Boolean>
<Array>
<Name>Output Bits</Name>
<Dimsize>38</Dimsize>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name>Output Bit</Name>
<Val>0</Val>
</Boolean>
</Array>
<Path>
<Name>Macro Path</Name>
<Val></Val>
</Path>
<Array>
<Name>Potentials</Name>
<Dimsize>18</Dimsize>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>20.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
<DBL>
<Name></Name>
<Val>0.00000000000000</Val>
</DBL>
</Array>
<Boolean>
<Name>Ramp/Point</Name>
<Val>0</Val>
</Boolean>
</Cluster>
</Array>
<Array>
<Name>Changes</Name>
<Dimsize>2</Dimsize>
<Dimsize>3</Dimsize>
<Boolean>
<Name></Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name></Name>
<Val>1</Val>
</Boolean>
<Boolean>
<Name></Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name></Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name></Name>
<Val>0</Val>
</Boolean>
<Boolean>
<Name></Name>
<Val>1</Val>
</Boolean>
</Array>
<String>
<Name>Macro Description</Name>
<Val></Val>
</String>
<DBL>
<Name>Total Time (s)</Name>
<Val>2.00000000000000E-3</Val>
</DBL>
<DBL>
<Name>Samples per sec</Name>
<Val>10000.00000000000000</Val>
</DBL>
</Cluster>
</LVData>